"""Markdown report exporter."""

from __future__ import annotations

from evalguard.report.schema import EvalGuardReport


class MarkdownExporter:
    """Exports an EvalGuardReport to a clean GitHub-flavored Markdown document."""

    @classmethod
    def export(cls, report: EvalGuardReport) -> str:
        s = report.summary
        lines = [
            f"# EvalGuard Audit Report: {report.benchmark_id}",
            "",
            f"- **Report ID**: `{report.report_id}`",
            f"- **Agent ID**: `{report.agent_id}`",
            f"- **Harness**: `{report.harness_name}`",
            f"- **Timestamp**: {report.created_at.strftime('%Y-%m-%d %H:%M:%S UTC')}",
            f"- **Schema Version**: `v{report.schema_version}`",
            "",
            "## Executive Summary",
            "",
            "| Metric | Count | Percentage |",
            "| :--- | :---: | :---: |",
            f"| Total Tasks Audited | {s.total_tasks} | 100% |",
            f"| Nominal Passed Tasks | {s.agent_passed_tasks} | {(s.agent_passed_tasks / s.total_tasks * 100) if s.total_tasks else 0:.1f}% |",
            f"| **Verified Clean Passed Tasks** | **{s.clean_passed_tasks}** | **{(s.clean_passed_tasks / s.total_tasks * 100) if s.total_tasks else 0:.1f}%** |",
            f"| Boundary Violations Total | {s.boundary_violations_total} | - |",
            f"| Tasks with Violations | {s.tasks_with_violations} | {(s.tasks_with_violations / s.total_tasks * 100) if s.total_tasks else 0:.1f}% |",
            f"| Tasks with Reward Hacking | {s.tasks_with_reward_hack} | {(s.tasks_with_reward_hack / s.total_tasks * 100) if s.total_tasks else 0:.1f}% |",
            f"| Contaminated Tasks | {s.tasks_with_contamination} | {(s.tasks_with_contamination / s.total_tasks * 100) if s.total_tasks else 0:.1f}% |",
            f"| Suspect or Invalid Tests | {s.suspect_or_invalid_tests} | {(s.suspect_or_invalid_tests / s.total_tasks * 100) if s.total_tasks else 0:.1f}% |",
            "",
            "## Task Breakdown",
            "",
            "| Task ID | Agent Passed | Violations | Reward Hack Score | Contaminated? | Test Integrity |",
            "| :--- | :---: | :---: | :---: | :---: | :---: |",
        ]

        for t in report.tasks:
            agent_str = "PASS" if t.agent_passed else "FAIL"
            viol_str = str(len(t.violations)) if t.violations else "0"
            hack_score = f"{t.reward_hack.confidence_score:.2f}" if t.reward_hack else "0.00"
            contam = "YES" if any(cf.is_contaminated for cf in t.contamination_flags) else "NO"
            t_status = t.test_integrity.status.value if t.test_integrity else "PASS"
            lines.append(
                f"| `{t.task_id}` | {agent_str} | {viol_str} | {hack_score} | {contam} | {t_status} |"
            )

        lines.extend(
            [
                "",
                "---",
                "*Generated by EvalGuard — Benchmark Integrity Infrastructure for Agent Evaluations*",
            ]
        )
        return "\n".join(lines)
